# Generated by Django 4.0.4 on 2022-06-30 11:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medbase', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_number', models.CharField(max_length=150, verbose_name='номер пациента')),
                ('fio', models.CharField(max_length=100, verbose_name='ФИО')),
                ('data_birthday', models.DateField(verbose_name='дата рождения')),
                ('number_oms', models.CharField(max_length=40, verbose_name='номер полиса')),
                ('adres', models.CharField(max_length=200, verbose_name='адрес проживания')),
                ('phone', models.CharField(max_length=200, verbose_name='телефон')),
            ],
            options={
                'verbose_name': 'Пациента',
                'verbose_name_plural': 'Пациенты',
                'ordering': ['fio'],
            },
        ),
        migrations.AlterField(
            model_name='personal',
            name='stuff_name',
            field=models.CharField(max_length=150, verbose_name='должность'),
        ),
        migrations.CreateModel(
            name='Urea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_work', models.DateField(verbose_name='дата приема анализа')),
                ('belock', models.CharField(max_length=10, verbose_name='белок')),
                ('sugar', models.CharField(max_length=10, verbose_name='сахар')),
                ('mochevina', models.CharField(max_length=10, verbose_name='мочевина')),
                ('text_urea', models.CharField(max_length=100, verbose_name='описание')),
                ('patient_number', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='medbase.patient', verbose_name='номер пациента')),
            ],
            options={
                'verbose_name': 'Анализ мочи',
                'verbose_name_plural': 'Анализы мочи',
                'ordering': ['-data_work'],
            },
        ),
        migrations.CreateModel(
            name='MedWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_work', models.DateField(verbose_name='дата приема')),
                ('content_work', models.TextField(max_length=1000, verbose_name='описание приема')),
                ('recomend_work', models.CharField(max_length=200, verbose_name='рекомендации')),
                ('patient_number', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='medbase.patient', verbose_name='номер пациента')),
            ],
            options={
                'verbose_name': 'Прием',
                'verbose_name_plural': 'Приемы',
                'ordering': ['-data_work'],
            },
        ),
        migrations.CreateModel(
            name='Blood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_work', models.DateField(verbose_name='дата приема анализа')),
                ('belock', models.CharField(max_length=10, verbose_name='белок')),
                ('hgb', models.CharField(max_length=10, verbose_name='ХГБ')),
                ('sugar', models.CharField(max_length=10, verbose_name='сахар')),
                ('text_blood', models.CharField(max_length=100, verbose_name='описание')),
                ('patient_number', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='medbase.patient', verbose_name='номер пациента')),
            ],
            options={
                'verbose_name': 'Анализ крови',
                'verbose_name_plural': 'Анализы крови',
                'ordering': ['-data_work'],
            },
        ),
    ]
