# Generated by Django 4.0.4 on 2022-06-21 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Обращение', 'verbose_name_plural': 'Обращения'},
        ),
        migrations.AlterModelOptions(
            name='statuscrm',
            options={'verbose_name': 'Статус обращения', 'verbose_name_plural': 'Статусы обращений'},
        ),
        migrations.AddField(
            model_name='order',
            name='order_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Электронная почта'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_phone',
            field=models.IntegerField(max_length=11, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='statuscrm',
            name='status_name',
            field=models.CharField(max_length=200, verbose_name='Название статуса обращения'),
        ),
    ]
