# Generated by Django 4.0.4 on 2022-06-21 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_alter_order_options_alter_statuscrm_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_context',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Сообщение'),
        ),
    ]
