# Generated by Django 4.0.4 on 2022-06-21 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_order_order_context'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_email',
            field=models.EmailField(blank=True, max_length=100, null=True, verbose_name='Электронная почта'),
        ),
    ]
