# Generated by Django 4.0.4 on 2022-06-30 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_alter_order_order_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_phone',
            field=models.CharField(max_length=11, verbose_name='Телефон'),
        ),
    ]
