# Generated by Django 4.0.4 on 2022-07-07 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_index'),
    ]

    operations = [
        migrations.AlterField(
            model_name='index',
            name='content',
            field=models.TextField(verbose_name='контент'),
        ),
    ]
