# Generated by Django 4.0.4 on 2022-07-07 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_index_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='index',
            name='title',
            field=models.CharField(blank=True, max_length=200, verbose_name='Наименование больницы'),
        ),
    ]
